version: '3'
services:
  frontend-service:
    build: ./frontend
    ports:
      - '3000:3000'
  backend-service:
    build:
      context: ./backend
      args:
        - CREDENTIALS_JSON=./credentials.json
    ports:
      - '8000:8000'