version: '3'
services:
  frontend-service:
    build: ./frontend
    environment:
      - APP_ENV=development
    ports:
      - '3000:3000'
  backend-service:
    build: ./backend
    ports:
      - '8000:8000'