apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/automateml/backend-docker-image/backend:latest
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 50Mi
          ports:
            - name: http
              containerPort: 80
