# This file is used to create a single running instance (a pod/container) of the back-end application in the GKE cluster. 
# This application is built from the backend Docker image stored in the Artifact Registry. 
# The application listens on port 8000 for incoming network traffic.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # uses the back-end image from the artifact registry 
        image: us-central1-docker.pkg.dev/automate-gdsc/backend-images/backend:latest
        ports:
        - containerPort: 8000
