# This file is used to deploy a single running instance (a pod/container) of the front-end application.
# This application is built from the frontend Docker image stored in the Artifact Registry
# The application listens on port 3000 for incoming network traffic.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # uses the front-end image from the artifact registry
        image: us-central1-docker.pkg.dev/automate-gdsc/frontend-images/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_ENV
          value: "production"
