# Download vscode REST Client extension and press "send request" under each commented header
# make sure you have the up to data credentials.json in the root of your whole repo

#### Root test
GET http://127.0.0.1:8000/

#### Python test
GET http://127.0.0.1:8000/api/python

#### Get Datasets
GET http://127.0.0.1:8000/api/datasets

#### BigQuery test
GET http://127.0.0.1:8000/api/bq?fileName=sample_contacts

#### Get Data
GET http://127.0.0.1:8000/api/data?fileName=data.csv

#### Get Profile
GET http://127.0.0.1:8000/api/eda-profile?fileName=data

#### Get AutoML
GET http://127.0.0.1:8000/api/automl

#### Upload data set
PUT http://127.0.0.1:8000/api/upload
Content-Type: multipart/form-data; boundary=yourBoundary

--yourBoundary
Content-Disposition: form-data; name="fileName"

mo11.csv
--yourBoundary
Content-Disposition: form-data; name="file"; filename="data.csv"
Content-Type: text/csv

< ../data.csv
--yourBoundary--

#### Get eda
GET http://127.0.0.1:8000/api/eda?fileName=data