name: Deploy Backend Dockerfile to Artifact Regitry 

on:
    push:
        branches:
            - 'main'
  
jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
        - name: code checkout
          uses: actions/checkout@v4

        - name: install gcloud cli
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: automateml
            service_account_key: ${{secrets.GCP_SA_KEY}}
            export_default_credentials: true
        
        - name: build and push docker image
          env:
            GOOGLE_PROJECT: automateml
          run: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            docker build -t us-central1-docker.pkg.dev/automateml/backend-docker-image/backend:latest ./backend
            docker push us-central1-docker.pkg.dev/automateml/backend-docker-image/backend:latest 
