name: "Provision K8s manifests"

on:
  workflow_dispatch:

jobs:
  kubernetes:
    name: "Provision K8s manifests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.OWNER_SA_KEY }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials automl-cluster --region us-east1-b --project automateml

      - name: Deploy to GKE
        run: |
          kubectl apply -f cloud-infra/k8s/
