name: "Manual K8s Deployment"

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  kubernetes:
    name: "Deploy K8s manifests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials automl-cluster --region us-east1 --project automateml

      - name: Deploy to GKE
        run: |
          kubectl apply -f cloud-infra/k8s/
