name: "Manually Provision Terraform"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Provision Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.OWNER_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: "Setup GCP Credentials"
        env:
          GCP_OWNER_SA_KEY: ${{ secrets.OWNER_SA_KEY }}
        run: |
          echo "$GCP_OWNER_SA_KEY" > ./cloud-infra/credentials.json

      - name: Terraform Init
        working-directory: ./cloud-infra
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: ./cloud-infra
        run: |
          terraform plan

      - name: Hold for approval
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 180 #will wait for 3 minutes for approval to be given, if not given, will abort
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        working-directory: ./cloud-infra
        if: github.event_name == 'workflow_dispatch'
        run: |
          terraform apply -auto-approve
