name: 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - 'cloud-infra/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      DEFAULT_SA_KEY: ${{ secrets.DEFAULT_SA_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform credentials
        run: |
          echo "GOOGLE_CREDENTIALS=${{ secrets.DEFAULT_SA_KEY }}" >> $GITHUB_ENV

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.DEFAULT_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
